x-podman:
  in_pod: false

services:
  mazanoke:
    image: ghcr.io/civilblur/mazanoke:latest
    container_name: mazanoke
    hostname: mazanoke
    restart: on-failure:3
    mem_limit: 1000m
    env_file:
      - ./.settings.env
    labels:
      caddy: http://optimise.example.lan, optimise.example.com
      caddy.reverse_proxy: "{{ upstreams }}"
      caddy.header: "-X-Frame-Options"
      caddy.log:
      caddy.sablier.session_duration: 5m
      caddy.sablier.names: mazanoke
      caddy.sablier.dynamic:
      sablier.enable: true
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 2m30s
      timeout: 10s
      retries: 1
      start_interval: 3s
      start_period: 6s
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy